### PR TITLE
fix(signals): handle shutdown signals cleanly on failed startup

### LINKED ISSUE #27: [Bug] Agent blocks graceful shutdown if it didn't start cleanly
## Description:

`smoketest.sh`: add this sample app config
```bash
    podman run \
        --name quarkus-test-agent-0 \
        --pod cryostat-pod \
        --env JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -javaagent:/deployments/app/cryostat-agent.jar" \
        --env QUARKUS_HTTP_PORT=10009 \
        --env ORG_ACME_CRYOSTATSERVICE_ENABLED="false" \
        --rm -d quay.io/andrewazores/quarkus-test:latest
```

Run `sh smoketest.sh`, let everything spin up.

`podman logs quarkus-test-agent-0`:
```
Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
INFO exec  java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -javaagent:/deployments/app/cryostat-agent.jar -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/quarkus-run.jar 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/deployments/app/cryostat-agent.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/deployments/lib/main/org.jboss.slf4j.slf4j-jboss-logmanager-1.1.0.Final.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Slf4jLoggerFactory]
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-12-23 20:38:58,013 INFO  [io.cry.age.Agent] (cryostat-agent) Cryostat Agent starting...
2022-12-23 20:39:00,678 INFO  [io.cry.cor.net.JFRConnectionToolkit] (cryostat-agent) Computed self JVM ID: 7Rprt-Rwnu9Pc4qkKe7G1nDZw6_s6fT2Ry--P8vNZXw=
2022-12-23 20:39:00,746 SEVERE [io.cry.age.Agent] (cryostat-agent) Agent startup failure: java.util.NoSuchElementException: SRCFG00040: The config property cryostat.agent.baseuri is defined as the empty String ("") which the following Converter considered to be null: io.smallrye.config.ImplicitConverters$ConstructorConverter
	at io.smallrye.config.SmallRyeConfig.convertValue(SmallRyeConfig.java:284)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:239)
	at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:167)
	at io.cryostat.agent.ConfigModule.provideCryostatAgentBaseUri(ConfigModule.java:91)
	at io.cryostat.agent.ConfigModule_ProvideCryostatAgentBaseUriFactory.provideCryostatAgentBaseUri(ConfigModule_ProvideCryostatAgentBaseUriFactory.java:36)
	at io.cryostat.agent.ConfigModule_ProvideCryostatAgentBaseUriFactory.get(ConfigModule_ProvideCryostatAgentBaseUriFactory.java:27)
	at io.cryostat.agent.ConfigModule_ProvideCryostatAgentBaseUriFactory.get(ConfigModule_ProvideCryostatAgentBaseUriFactory.java:10)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at io.cryostat.agent.MainModule_ProvideCryostatClientFactory.get(MainModule_ProvideCryostatClientFactory.java:48)
	at io.cryostat.agent.MainModule_ProvideCryostatClientFactory.get(MainModule_ProvideCryostatClientFactory.java:10)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at io.cryostat.agent.MainModule_ProvideRegistrationFactory.get(MainModule_ProvideRegistrationFactory.java:55)
	at io.cryostat.agent.MainModule_ProvideRegistrationFactory.get(MainModule_ProvideRegistrationFactory.java:10)
	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
	at io.cryostat.agent.DaggerAgent_Client.registration(DaggerAgent_Client.java:117)
	at io.cryostat.agent.Agent.main(Agent.java:99)
	at io.cryostat.agent.Agent.lambda$agentmain$5(Agent.java:122)
	at java.base/java.lang.Thread.run(Thread.java:833)

2022-12-23 20:39:03,896 INFO  [io.quarkus] (main) quarkus-test 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.7.2.Final) started in 5.819s. Listening on: http://0.0.0.0:10009
2022-12-23 20:39:03,897 INFO  [io.quarkus] (main) Profile prod activated. 
2022-12-23 20:39:03,897 INFO  [io.quarkus] (main) Installed features: [cdi, rest-client, rest-client-jackson, resteasy, smallrye-context-propagation, vertx]
```

`Ctrl-c` to tear down `smoketest.sh`:
```
...
^C+ cleanup
+ podman pod stop cryostat-pod
WARN[0010] StopSignal SIGTERM failed to stop container quarkus-test-agent-0 in 10 seconds, resorting to SIGKILL
```

## Expected:

If any required configuration property is not set, the Agent should gracefully handle this and fail to start. `SIGTERM`ing the JVM should result in a normal clean shutdown.

### PR DESCRIPTION
**Pull request by andrewazores**
Fixes #27
Replaces #43

### CODE REVIEW

File: src/main/java/io/cryostat/agent/Agent.java [hunk 1]
```diff
@@ -55,71 +59,56 @@ public class Agent {
...
+    private static AgentExitHandler installSignalHandlers(
+            final Registration registration,
+            final Harvester harvester,
+            final WebServer webServer,
+            final ExecutorService executor) {
+        AgentExitHandler agentExitHandler =
+                new AgentExitHandler(registration, harvester, webServer, executor);
+        for (String s : List.of("INT", "TERM", "QUIT")) {
+            Signal signal = new Signal(s);
+            SignalHandler oldHandler = Signal.handle(signal, agentExitHandler);
```
Comment (maxcao13) [inline src/main/java/io/cryostat/agent/Agent.java:108]: What exactly is the purpose of these couple lines? Seems like a lot of passing signal handlers back and forth.

File: src/main/java/io/cryostat/agent/Agent.java [hunk 2]
```diff
@@ -154,4 +143,74 @@ interface Builder {
...
+        public void handle(Signal sig) {
+            log.info("Caught SIG{}({})", sig.getName(), sig.getNumber());
+            try {
+                harvester.exitUpload().get();
+            } catch (InterruptedException | ExecutionException e) {
+                log.error("Exit upload failed", e);
+            } finally {
+                registration
+                        .deregister()
+                        .orTimeout(3, TimeUnit.SECONDS)
```
Comment (maxcao13) [inline src/main/java/io/cryostat/agent/Agent.java:182]: Magic number 3?

**Review by maxcao13 — COMMENTED** [review]
Other than those few questions, looks good and the bug is fixed.

File: src/main/java/io/cryostat/agent/Agent.java (hunk 1 above)
Comment (andrewazores) [reply src/main/java/io/cryostat/agent/Agent.java:108]: Yea, it is. The Signal API only allows for installing a new handler, and the return value is the old handler - it isn't adding a new one to a collection of listeners, it's replacing it. But the Agent should not be completely changing the way that the application it's attached to handles signals, it should only be catching the signals so that it can perform its own cleanup, and then forward those signals on to whatever other signal handler may have been there first, including the default one that just initiates a standard JVM shutdown.

`Runtime.addShutdownHook` looks like it should be the same job for us here, but in practice I found that at least some web application frameworks handle signals and cause a shutdown that doesn't give the agent's hook enough time to execute before the whole application is shut down, so the exit upload we want to perform gets interrupted every time. Going a layer lower in the stack and directly intercepting signals means the agent is able to perform blocking actions that prevent shutdown (which was the source of the original bug here). There is still the onus to properly pass the signal on and to complete our shutdown tasks in a reasonable timeframe, lest we get `SIGKILL`ed.

Comment (maxcao13) [reply src/main/java/io/cryostat/agent/Agent.java:108]: Wow very interesting! Lot's of information I did not know, thanks for the writeup.

File: README.md [hunk 3]
```diff
@@ -44,6 +44,7 @@ and how it advertises itself to a Cryostat server instance. Required properties
 - [ ] `cryostat.agent.app.name` [`String`]: a human-friendly name for this application. Default `cryostat-agent`.
 - [ ] `cryostat.agent.app.jmx.port` [`int`]: the JMX RMI port that the application is listening on. The default is to attempt to determine this from the `com.sun.management.jmxremote.port` system property.
 - [ ] `cryostat.agent.registration.retry-ms` [`long`]: the duration in milliseconds between attempts to register with the Cryostat server. Default `5000`.
+- [ ] `cryostat.agent.exit.deregistration.timeout` [`Duration`]: the duration to wait for a response from the Cryostat server when attempting to deregister at shutdown time . Default `3s`.
```
Comment (maxcao13) [inline README.md]: Should this be specific in that it needs a property of ms?

Comment (andrewazores) [reply README.md]: Not sure what happened here, I already made that change in one of the last commits that was pushed before this comment, but it isn't showing this comment as outdated...

Comment (andrewazores) [reply README.md]: I was trying to get SmallRye Config to let me use Duration instead of `long` so that the config values could be like `1s` or `500ms` instead of always being written out in `ms`, but it needs some extra converter added to parse text to Durations like that, so I dropped it and went back to just specifying it in `ms`.

File: README.md [hunk 4]
```diff
@@ -37,16 +37,21 @@ and how it advertises itself to a Cryostat server instance. Required properties
 - [ ] `cryostat.agent.hostname` [`String`]: the hostname for this application instance. This will be used for the published JMX connection URL. If not provided then the default is to attempt to resolve the localhost hostname.
 - [ ] `cryostat.agent.realm` [`String`]: the Cryostat Discovery API "realm" that this agent belongs to. This should be unique per agent instance. The default includes the `cryostat.agent.app.name` and a random UUID.
 - [ ] `cryostat.agent.authorization` [`String`]: Authorization header value to include with API requests to the Cryostat server, ex. `Bearer abcd1234`. Default `None`.
-- [ ] `cryostat.agent.ssl.trust-all` [`boolean`]: Control whether the agent trusts all certificates presented by the Cryostat server. Default `true`.
-- [ ] `cryostat.agent.ssl.verify-hostname` [`boolean`]: Control whether the agent verifies hostnames on certificates presented by the Cryostat server. Default `false`.
+- [ ] `cryostat.agent.webclient.ssl.trust-all` [`boolean`]: Control whether the agent trusts all certificates presented by the Cryostat server. Default `true`.
```
Comment (tthvo) [inline README.md:40]: Update README to match defaults in latest commits?

File: src/main/java/io/cryostat/agent/Agent.java [hunk 5]
```diff
@@ -53,73 +59,86 @@
...
-            client.webServer().start();
+            t.setName("cryostat-agent-shutdown");
+            t.setDaemon(false);
+            Runtime.getRuntime().addShutdownHook(t);
+
+            registration.addRegistrationListener(
+                    evt -> {
+                        switch (evt.state) {
+                            case REGISTERED:
+                                client.harvester().start();
```
Comment (tthvo) [inline src/main/java/io/cryostat/agent/Agent.java:99]: Use the extracted `harvester` variable above?

**Review by tthvo — COMMENTED** [review]
Looks good and fixed the issue^^ Just some small refactoring and docs comments.

**Review by tthvo — APPROVED** [review]
Looks good to me :D
