### PR TITLE
fix(recordings): handle null maxAge

### LINKED ISSUE #117: [Bug] SEVERE: recordings serialization failure java.lang.NullPointerException: Cannot invoke "java.time.Duration.toMillis()"
```
May 05, 2023 8:23:29 PM io.cryostat.agent.remote.RecordingsContext handle
SEVERE: recordings serialization failure
java.lang.NullPointerException: Cannot invoke "java.time.Duration.toMillis()" because the return value of "jdk.jfr.Recording.getMaxAge()" is null
	at io.cryostat.agent.remote.RecordingsContext$RecordingInfo.<init>(RecordingsContext.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.cryostat.agent.remote.RecordingsContext.getRecordings(RecordingsContext.java:99)
	at io.cryostat.agent.remote.RecordingsContext.handle(RecordingsContext.java:78)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
	at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:71)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:851)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:95)
	at io.cryostat.agent.WebServer$CompressionFilter.doFilter(WebServer.java:267)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
	at io.cryostat.agent.WebServer$RequestLoggingFilter.doFilter(WebServer.java:212)
	at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
	at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:818)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### PR DESCRIPTION
**Pull request by andrewazores**
Fixes #117

### CODE REVIEW

File: src/main/java/io/cryostat/agent/remote/RecordingsContext.java [hunk 1]
```diff
@@ -123,7 +123,11 @@ private static class RecordingInfo {
             this.duration = this.isContinuous ? 0 : rec.getDuration().toMillis();
             this.toDisk = rec.isToDisk();
             this.maxSize = rec.getMaxSize();
```
Comment (ebaron) [inline src/main/java/io/cryostat/agent/remote/RecordingsContext.java:125]: Does this not happen with max size or any of the other options?

Comment (andrewazores) [reply src/main/java/io/cryostat/agent/remote/RecordingsContext.java:125]: Good call, it can happen to `startTime` if the recording has been created but not yet started. I think the others are all either non-nullable types - `maxSize` is a `long` - or have API docs saying they are not null (like the `name`).

Comment (ebaron) [reply src/main/java/io/cryostat/agent/remote/RecordingsContext.java:129]: Can state be null?

Comment (andrewazores) [reply src/main/java/io/cryostat/agent/remote/RecordingsContext.java:129]: The `recording.getState()` has a javadoc saying it's `not null`, and it's an enum type so the `.name()` will also be not null.

Comment (andrewazores) [reply src/main/java/io/cryostat/agent/remote/RecordingsContext.java:129]: https://docs.oracle.com/en/java/javase/11/docs/api/jdk.jfr/jdk/jfr/Recording.html#getState()

Comment (ebaron) [reply src/main/java/io/cryostat/agent/remote/RecordingsContext.java:129]: Sounds good

**Review by ebaron — APPROVED** [review]
