### PR TITLE
fix(http): use Apache HTTP client

### LINKED ISSUE #54: [Bug] `POST` to Cryostat failure
Logs from the Cryostat backend:

```
Caused by: io.cryostat.net.web.http.api.v2.ApiException: No recording submission
	at io.cryostat.net.web.http.api.beta.RecordingsFromIdPostHandler.handleAuthenticated(RecordingsFromIdPostHandler.java:201)
	at io.cryostat.net.web.http.AbstractAuthenticatedRequestHandler.handle(AbstractAuthenticatedRequestHandler.java:102)
	at io.cryostat.net.web.http.AbstractAuthenticatedRequestHandler.handle(AbstractAuthenticatedRequestHandler.java:72)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:93)
	at io.vertx.ext.web.handler.impl.BodyHandlerImpl.handle(BodyHandlerImpl.java:46)
	at io.cryostat.net.web.http.api.beta.RecordingsFromIdPostBodyHandler.handleAuthenticated(RecordingsFromIdPostBodyHandler.java:117)
	at io.cryostat.net.web.http.AbstractAuthenticatedRequestHandler.handle(AbstractAuthenticatedRequestHandler.java:102)
	at io.cryostat.net.web.http.AbstractAuthenticatedRequestHandler.handle(AbstractAuthenticatedRequestHandler.java:72)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:189)
	at io.vertx.ext.web.handler.impl.CorsHandlerImpl.handle(CorsHandlerImpl.java:41)
	at io.cryostat.net.web.http.generic.CorsEnablingHandler.handle(CorsEnablingHandler.java:131)
	at io.cryostat.net.web.http.generic.CorsEnablingHandler.handle(CorsEnablingHandler.java:63)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.vertx.ext.web.handler.impl.LoggerHandlerImpl.handle(LoggerHandlerImpl.java:189)
	at io.vertx.ext.web.handler.impl.LoggerHandlerImpl.handle(LoggerHandlerImpl.java:48)
	at io.cryostat.net.web.http.generic.RequestLoggingHandler.handle(RequestLoggingHandler.java:123)
	at io.cryostat.net.web.http.generic.RequestLoggingHandler.handle(RequestLoggingHandler.java:65)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:68)
	at io.vertx.ext.web.impl.RouterImpl.handle(RouterImpl.java:37)
	at io.cryostat.net.HttpServer$HandlerDelegate.handle(HttpServer.java:168)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:55)
	at io.vertx.core.impl.DuplicatedContext.emit(DuplicatedContext.java:158)
	at io.vertx.core.http.impl.Http2ServerRequest.dispatch(Http2ServerRequest.java:122)
	at io.vertx.core.http.impl.Http2ServerStream.onHeaders(Http2ServerStream.java:96)
	at io.vertx.core.http.impl.Http2ServerConnection.onHeadersRead(Http2ServerConnection.java:155)
	at io.vertx.core.http.impl.Http2ConnectionBase.onHeadersRead(Http2ConnectionBase.java:202)
	at io.vertx.core.http.impl.Http2ServerConnection.onHeadersRead(Http2ServerConnection.java:44)
	at io.netty.handler.codec.http2.Http2FrameListenerDecorator.onHeadersRead(Http2FrameListenerDecorator.java:48)
	at io.netty.handler.codec.http2.Http2EmptyDataFrameListener.onHeadersRead(Http2EmptyDataFrameListener.java:63)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:409)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onHeadersRead(DefaultHttp2ConnectionDecoder.java:337)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onHeadersRead(Http2InboundFrameLogger.java:56)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader$2.processFragment(DefaultHttp2FrameReader.java:476)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readHeadersFrame(DefaultHttp2FrameReader.java:484)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:253)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173)
	at io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:393)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:519)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:458)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:280)
	at io.vertx.core.http.impl.VertxHttp2ConnectionHandler.channelRead(VertxHttp2ConnectionHandler.java:408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Feb 06, 2023 6:59:43 PM org.slf4j.impl.JDK14LoggerAdapter fillCallerData
WARNING: 127.0.0.1 - - [Mon, 6 Feb 2023 18:59:43 GMT] 2ms "POST /api/beta/recordings/AAl-2I7mLgO4H2DtGz1gApO8nIVGgvrGmA2Q6AC482A= HTTP/2.0" 400 97 bytes "-" "Java-http-client/17.0.5"
```

The `-agent` logs just show a generic `400` error response when the harvester attempts to push a file to storage.

### PR DESCRIPTION
**Pull request by andrewazores**
Fixes #54

Replaces the JDK HTTP Client with Apache HTTP Client. This is a more robust and easier to use library, and also fixes the above bug.

To test:
1. `mvn install` to get the JAR into local mvn repo
2. `cd quarkus-test ; ./mvnw package && podman build -t quay.io/andrewazores/quarkus-test:latest -f src/main/docker/Dockerfile.jvm . ; podman image prune -f` to build a `quarkus-test` using this updated agent JAR
3. `cd cryostat ; sh smoketest.sh` to run the smoketest setup. `quarkus-test-agent-{0,1,2}` should spin up, each using the new Agent JAR containing this change. `0` should fail to register itself due to a missing environment variable, but the host application should run as usual. `1` should register itself successfully and then periodically push harvested JFR files. `2` should register itself and do nothing further.
4. `^C` on smoketest.sh to tear down. All three `quarkus-test-agent` instances should cleanly exit along with everything else.

### CODE REVIEW

**Review by maxcao13 — APPROVED** [review]
Implementation looks good and the code makes sense!

File: src/main/java/io/cryostat/agent/MainModule.java [hunk 1]
```diff
@@ -146,21 +150,28 @@ public X509Certificate[] getAcceptedIssuers() {
...
+                    boolean verifyHostname) {
+        HttpClientBuilder builder =
+                HttpClients.custom()
+                        .setDefaultHeaders(Set.of(new BasicHeader("Authorization", authorization)))
+                        .setSSLContext(sslContext)
+                        .setDefaultRequestConfig(
+                                RequestConfig.custom()
+                                        .setAuthenticationEnabled(true)
+                                        .setExpectContinueEnabled(true)
+                                        .setConnectTimeout(5000)
```
Comment (tthvo) [inline src/main/java/io/cryostat/agent/MainModule.java:165]: Should these timeout values taken from envs (e.g. `CRYOSTAT_AGENT_WEBCLIENT_CONNECT_TIMEOUT_MS`)?

**Review by tthvo — COMMENTED** [review]
Looks good to me! Not sure if related to this PR but I have been having issue that the agent could not re-register itself when running smoketest.


```log
2023-02-10 08:01:07,860 INFO  [io.cry.age.CryostatClient] (cryostat-agent-worker-2) POST https://localhost:8181/api/v2.2/discovery HTTP/1.1
2023-02-10 08:01:07,867 INFO  [io.cry.age.CryostatClient] (cryostat-agent-worker-0) POST https://localhost:8181/api/v2.2/discovery : 400
2023-02-10 08:01:07,867 SEVERE [io.cry.age.CryostatClient] (cryostat-agent-worker-0) Non-OK response (400) on HTTP API https://localhost:8181/api/v2.2/discovery
2023-02-10 08:01:07,867 SEVERE [io.cry.age.Registration] (cryostat-agent-worker-2) Registration failure: java.util.concurrent.ExecutionException: io.cryostat.agent.RegistrationException: java.util.concurrent.CompletionException: io.cryostat.agent.HttpException: Unexpected non-OK status code 400 on API path https://localhost:8181/api/v2.2/discovery
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
	at io.cryostat.agent.Registration.tryRegister(Registration.java:133)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.cryostat.agent.RegistrationException: java.util.concurrent.CompletionException: io.cryostat.agent.HttpException: Unexpected non-OK status code 400 on API path https://localhost:8181/api/v2.2/discovery
	at io.cryostat.agent.Registration.lambda$tryRegister$0(Registration.java:126)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	... 6 more
Caused by: java.util.concurrent.CompletionException: io.cryostat.agent.HttpException: Unexpected non-OK status code 400 on API path https://localhost:8181/api/v2.2/discovery
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	... 6 more
Caused by: io.cryostat.agent.HttpException: Unexpected non-OK status code 400 on API path https://localhost:8181/api/v2.2/discovery
	at io.cryostat.agent.CryostatClient.assertOkStatus(CryostatClient.java:286)
	at io.cryostat.agent.CryostatClient.lambda$register$1(CryostatClient.java:129)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 8 more

2023-02-10 08:01:07,867 INFO  [io.cry.age.Registration] (cryostat-agent-worker-2) Registration retry period: PT5S
```

When the agent exits, I am seeing this:

```logs
2023-02-10 08:01:08,020 INFO  [io.cry.age.Registration] (cryostat-agent-worker-1) Registration retry period: PT5S
2023-02-10 08:01:09,025 INFO  [io.cry.age.Agent] (SIGTERM handler) Caught SIGTERM(15)
2023-02-10 08:01:09,026 INFO  [io.cry.age.Agent] (SIGTERM handler) Performing cleanup...
2023-02-10 08:01:09,026 INFO  [io.cry.age.Registration] (SIGTERM handler) Deregistration requested before registration complete!
2023-02-10 08:01:09,026 INFO  [io.cry.age.Agent] (cryostat-agent-worker-0) Shutting down...
2023-02-10 08:01:09,028 INFO  [io.cry.age.Agent] (cryostat-agent-worker-0) Shutdown complete
2023-02-10 08:01:09,061 INFO  [io.quarkus] (Shutdown thread) quarkus-test stopped in 0.033s
```

Maybe I am confused :D?

File: src/main/java/io/cryostat/agent/MainModule.java (hunk 1 above)
Comment (andrewazores) [reply src/main/java/io/cryostat/agent/MainModule.java:165]: Oh good catch, thanks. I didn't catch on to that when I was rebasing this work.

**Comment by andrewazores** [comment]
re. logs ^

The second log part makes sense because as you say, it's just describing that it was still trying to register itself and never succeeded before shutting down.

The first part I have seen before with the smoketest when using `h2file/postgres` because the database ends up with stale data, essentially. I don't remember the exact details from the last time I traced this down. Basically this is a consequence of a timing issue on shutdown, and then the fact that the smoketest script spins up the target applications with their agents before the Cryostat server. So when Cryostat comes online it checks the database, sees existing definitions for targets, and tries to ping their callbacks to check if they are still around. It finds that they are, so it preserves the existing registration record. But then this conflicts with the agent's attempt to re-register itself since it is in fact a new instance.

I think the quick and easy development fix is to just tear down the smoketest pod and then delete your postgres/h2file database. The slower and more realistic fix would be to stop the target application and leave it stopped for long enough that Cryostat retries pinging its callback URL, sees that it is gone, and removes the registration record. Then the target application can be restarted and it should be able to register properly again.

**Comment by andrewazores** [comment]
Oh, and I've seen the interaction above when using the JDK HTTP client, not with the Apache HTTP client, so I don't believe the behaviour there is affected by this PR. Unless the root cause is something totally different I think it's unrelated to this PR.

**Review by tthvo — APPROVED** [review]
Ahh okayy makes sense! Looks good to me :D

**Comment by andrewazores** [comment]
Last check, waiting for @ebaron to confirm ability/willingness to carry this dependency for downstream.

**Review by ebaron — APPROVED** [review]
These dependencies should be fine.
